#!/usr/bin/env bash
set -euo pipefail

pgrep talon && exit 0

export TERM=xterm-256color
export NIXPKGS_ALLOW_UNFREE=1

notify-send "Starting talon..."

channel='https://github.com/NixOS/nixpkgs/archive/f28f4b4d2d3e83479b82be478ebf31601d54fe4d.tar.gz'  # NixOS release-25.11 as of 2025-12-17
pgrep snixembed || snixembed &

rm -f ~/talon
nix build -Lvf $channel talon --out-link ~/talon

steam-run ~/talon/talon
