#!/usr/bin/env bash
set -euo pipefail

export TERM=xterm-256color
export NIXPKGS_ALLOW_UNFREE=1

channel='https://github.com/NixOS/nixpkgs/archive/c37ca420157f4abc31e26f436c1145f8951ff373.tar.gz'  # 2023-06-03 from NixOS release-23.05
pgrep snixembed || snixembed &
nix run -f $channel talon
