#!/usr/bin/env bash
set -euo pipefail

export TERM=xterm-256color
export NIXPKGS_ALLOW_UNFREE=1

channel='https://github.com/NixOS/nixpkgs/archive/9a40f18db37b7baf3b3e3b231a143bff754dbfbc.tar.gz'  # 2021-10-09
nix run -f $channel talon -c talon
